##############################################################
###  Loki Stack mit Grafana Dashboard

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki-stack
  namespace: kube-system


### Installiert Loki, Promtail und Grafana im Namespace "logging"
### Grafana wird als LoadBalancer bereitgestellt, damit es von außen erreichbar ist
### 
# Wichtig:
# Anmeldename wird auf "admin" gesetzt
# Passwort wird auf "grafana" gesetzt
# Hardcoded für Demo-Zwecke (bei gebrauch anpassen)
# -> Zeile 33 und 34!
### 
### Loki hat 10 GiB Speicherplatz für die Persistenz der Daten
### mit sidecar werden die Dashboards und Datasources automatisch in Grafana importiert (unten implementiert)


spec:
  chart: loki-stack
  repo: https://grafana.github.io/helm-charts
  version: 2.10.3
  targetNamespace: logging
  createNamespace: true
  valuesContent: |-
    grafana:
      enabled: true
      adminUser: admin
      adminPassword: grafana
      service:
        type: LoadBalancer
      sidecar:
        dashboards:
          enabled: true
          defaultFolderName: "Loki"
          label: grafana_dashboard
          labelValue: "1"
        datasources:
          enabled: true
          label: grafana_datasource

    loki:
      persistence:
        enabled: true
        size: 10Gi

    promtail:
      enabled: true
---
##############################################################
### Grafana Dashboard für Loki (ConfigMap)
### Wichtig ist, dass das Label "grafana_dashboard" selben Wert hat wie "labelValue" 
### ab Zeile 70 findet sich das Dashboard im JSON-Format, welches in Grafana importiert wird

apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-dashboard
  namespace: logging
  labels:
    grafana_dashboard: "1"
data:
  loki-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "loki",
            "uid": ""
          },
          "gridPos": {
            "h": 12,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 3,
          "options": {
            "dedupStrategy": "none",
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": false,
            "showLabels": false,
            "showTime": false,
            "sortOrder": "Descending",
            "wrapLogMessage": false
          },
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "loki"
              },
              "editorMode": "builder",
              "expr": "{app=\"express-web\"}",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Webserver-Log",
          "type": "logs"
        },
        {
          "datasource": {
            "type": "loki",
            "uid": ""
          },
          "gridPos": {
            "h": 11,
            "w": 24,
            "x": 0,
            "y": 12
          },
          "id": 1,
          "options": {
            "dedupStrategy": "none",
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": true,
            "showLabels": false,
            "showTime": true,
            "sortOrder": "Descending",
            "wrapLogMessage": false
          },
          "pluginVersion": "10.3.3",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "loki"
              },
              "editorMode": "builder",
              "expr": "{namespace=\"kube-system\"} |= `Error`",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Error Panel Kube-System",
          "type": "logs"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 39,
      "tags": [
        "loki"
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-2d",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Logging-Dashboard",
      "uid": "ba3ddc51-af54-4c24-95cd-cc10fb1c9084",
      "version": 1,
      "weekStart": ""
    }
