apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki-stack
  namespace: kube-system

spec:
  chart: loki-stack 
  repo: https://grafana.github.io/helm-charts 
  version: 2.10.3
  targetNamespace: logging
  createNamespace: true
  valuesContent: |-
    grafana:
      enabled: true
      adminUser: admin
      adminPassword: grafana
      service:
        type: LoadBalancer

    loki:
      persistence:
        enabled: true
        size: 10Gi
        
    promtail:
      enabled: true
