{
 "title": "Logging-Dashboard",
 "tags": [ "loki" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Webserver-Log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"default\"} |= ``"
    }
   ]
  },
  {
   "title": "Log Panel Kube-System",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{namespace=\"kube-system\"}"
    }
   ]
  },
  {
   "title": "Error Panel Kube-system",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"kube-system\"} |= `error`"
    }
   ]
  }
 ]
}