apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system

#
# Anmeldename wird auf "admin" gesetzt
# Passwort wird auf "grafana" gesetzt
# Hardcoded für Demo-Zwecke (bei gebrauch bitte anpassen)
# -> Zeile 23 und 24!
#

spec:
  chart: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 80.2.0
  targetNamespace: monitoring
  createNamespace: true
  valuesContent: |-
    grafana:
      enabled: true
      adminUser: admin
      adminPassword: grafana
      service:
        type: LoadBalancer

    prometheus:
      prometheusSpec:
        retention: 30d
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 10Gi