apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudserv7-nginx
  namespace: cloudserv7-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudserv7-nginx
  template:
    metadata:
      labels:
        app: cloudserv7-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
